version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      TMC_API_CONFIG_KEY: ${TMC_API_CONFIG_KEY}
      PORT: ${PORT}
    ports:
      - '4000:4000'
