name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tmc-backend:latest .
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io
      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tmc-backend:latest
        # run: docker push tmc-backend:latest


  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tmc-backend:latest
      - name: Delete old container
        run: docker rm -f tmc-backend-container
      - name: Run docker container
        run: docker run -d -p 4000:4000 -name tmc-backend-container ${{secrets.DOCKERHUB_USERNAME}}/tmc-backend

    # steps:
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
