name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/tmc-backend:latest .

  docker_push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io
      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/tmc-backend:latest

  # deploy:
  #   needs: build
  #   runs-on: [""]

    # steps:
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
