name: PR Docker Build

on:
  pull_request:
    branches: [ "main" ]

jobs:

  lint_and_test:
    runs-on: ubuntu-latest

    container:
      image: node:18.16.1-slim
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      # - name: Run tests
      #   run: npm test  # Or use the appropriate command for testing

  docker_build:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t tmc-backend:latest .

      - name: Remove Docker images
        run: |
          docker images -q tmc-backend | xargs -I {} docker rmi {}
        shell: bash
