name: PR Docker Build

on:
  pull_request:
    branches: [ "main" ]

jobs:

  lint_and_test:
    runs-on: ubuntu-latest

    container:
      image: node:18.16.1-slim
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      # - name: Run tests
      #   run: npm test  # Or use the appropriate command for testing

  docker_build:
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t tmc-backend:latest .

      - name: Stop and remove all containers and images of tmc-backend
        run: |
          docker stop $(docker ps -aqf "name=tmc-backend")
          docker rm $(docker ps -aqf "name=tmc-backend")
          docker rmi $(docker images -q tmc-backend)

      - name: Remove Docker container and image
        run: |
          docker container prune -f
          docker image prune -f
